create table if not exists site_content (
  slug text primary key,
  draft jsonb not null,
  published jsonb not null,
  updated_at timestamptz not null default now()
);

create table if not exists site_reviews (
  id bigint generated by default as identity primary key,
  name text not null,
  company text,
  date_label text not null,
  rating integer not null default 5,
  text text not null,
  initials text,
  status text not null default 'published',
  created_at timestamptz not null default now()
);

create table if not exists contact_submissions (
  id bigint generated by default as identity primary key,
  full_name text not null,
  email text not null,
  phone text,
  inquiry_type text,
  subject text not null,
  message text not null,
  attachment_name text,
  status text not null default 'new',
  created_at timestamptz not null default now()
);

insert into site_content (slug, draft, published)
values ('home', '{}'::jsonb, '{}'::jsonb)
on conflict (slug) do nothing;
