import "server-only";

import postgres from "postgres";
import {
  buildInitials,
  defaultSiteContent,
  normalizeSiteContent,
  type ReviewItem,
  type SiteContent,
} from "./site-content";

type Db = ReturnType<typeof postgres>;

type SiteContentRow = {
  slug: string;
  draft: unknown;
  published: unknown;
  updated_at: string;
};

type ReviewRow = {
  id: number;
  name: string;
  company: string | null;
  date_label: string;
  rating: number;
  text: string;
  initials: string | null;
  status: string;
  created_at: string;
};

type ContactRow = {
  id: number;
  full_name: string;
  email: string;
  phone: string | null;
  inquiry_type: string | null;
  subject: string;
  message: string;
  attachment_name: string | null;
  status: string;
  created_at: string;
};

let dbInstance: Db | null = null;
let schemaReady: Promise<void> | null = null;

function getDatabaseUrl() {
  const explicitUrl = process.env.SUPABASE_DB_URL || process.env.DATABASE_URL;
  if (explicitUrl) {
    return explicitUrl;
  }

  const projectUrl = process.env.SUPABASE_URL;
  const password = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.Supabase_Password;

  if (!projectUrl || !password) {
    return null;
  }

  const parsed = new URL(projectUrl);
  const projectRef = parsed.hostname.split(".")[0];

  return `postgresql://postgres:${encodeURIComponent(password)}@db.${projectRef}.supabase.co:5432/postgres?sslmode=require`;
}

export function getDb() {
  if (dbInstance) {
    return dbInstance;
  }

  const connectionString = getDatabaseUrl();
  if (!connectionString) {
    throw new Error(
      "Supabase database credentials are missing. Set SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY or Supabase_Password.",
    );
  }

  dbInstance = postgres(connectionString, {
    ssl: "require",
    max: 1,
    idle_timeout: 20,
  });

  return dbInstance;
}

export async function ensureSchema() {
  if (!schemaReady) {
    schemaReady = initializeSchema();
  }

  await schemaReady;
}

async function initializeSchema() {
  const sql = getDb();

  await sql`
    create table if not exists site_content (
      slug text primary key,
      draft jsonb not null,
      published jsonb not null,
      updated_at timestamptz not null default now()
    )
  `;

  await sql`
    create table if not exists site_reviews (
      id bigint generated by default as identity primary key,
      name text not null,
      company text,
      date_label text not null,
      rating integer not null default 5,
      text text not null,
      initials text,
      status text not null default 'published',
      created_at timestamptz not null default now()
    )
  `;

  await sql`
    create table if not exists contact_submissions (
      id bigint generated by default as identity primary key,
      full_name text not null,
      email text not null,
      phone text,
      inquiry_type text,
      subject text not null,
      message text not null,
      attachment_name text,
      status text not null default 'new',
      created_at timestamptz not null default now()
    )
  `;

  await sql`
    insert into site_content (slug, draft, published)
    values ('home', ${JSON.stringify(defaultSiteContent)}::jsonb, ${JSON.stringify(defaultSiteContent)}::jsonb)
    on conflict (slug) do nothing
  `;

  await ensureSeedTeamMember();
}

async function ensureSeedTeamMember() {
  const sql = getDb();

  const rows = await sql<SiteContentRow[]>`
    select slug, draft, published, updated_at
    from site_content
    where slug = 'home'
    limit 1
  `;

  const row = rows[0];
  if (!row) {
    return;
  }

  const draft = normalizeSiteContent(row.draft as Partial<SiteContent>);
  const published = normalizeSiteContent(row.published as Partial<SiteContent>);
  const seededMember = {
    name: "Sainee Kumar",
    role: "Data Analyst",
    initials: "SK",
    skills: ["Data Visualisation", "Data Cleaning", "Business Analysis"],
    bio:
      "Turns raw data into clear stories, actionable dashboards, and decisions that are easy for teams to trust.",
    portfolioUrl: "#contact",
    linkedinUrl: "#contact",
  };

  const addMember = (team: SiteContent["team"]) =>
    team.some((member) => member.name === seededMember.name) ? team : [...team, seededMember];

  const nextDraft = {
    ...draft,
    team: addMember(draft.team),
  };

  const nextPublished = {
    ...published,
    team: addMember(published.team),
  };

  if (JSON.stringify(nextDraft) === JSON.stringify(draft) && JSON.stringify(nextPublished) === JSON.stringify(published)) {
    return;
  }

  await sql`
    update site_content
    set draft = ${JSON.stringify(nextDraft)}::jsonb,
        published = ${JSON.stringify(nextPublished)}::jsonb,
        updated_at = now()
    where slug = 'home'
  `;
}

export async function getSiteContent(mode: "draft" | "published" = "published") {
  await ensureSchema();
  const sql = getDb();
  const rows = await sql<SiteContentRow[]>`
    select slug, draft, published, updated_at
    from site_content
    where slug = 'home'
    limit 1
  `;

  const row = rows[0];
  const content = row ? row[mode] : defaultSiteContent;

  return normalizeSiteContent(content as Partial<SiteContent>);
}

export async function saveSiteDraft(content: SiteContent) {
  await ensureSchema();
  const sql = getDb();

  await sql`
    insert into site_content (slug, draft, published)
    values ('home', ${JSON.stringify(content)}::jsonb, ${JSON.stringify(defaultSiteContent)}::jsonb)
    on conflict (slug) do update
    set draft = excluded.draft,
        updated_at = now()
  `;
}

export async function publishSiteDraft() {
  await ensureSchema();
  const sql = getDb();

  await sql`
    update site_content
    set published = draft,
        updated_at = now()
    where slug = 'home'
  `;
}

export async function listPublishedReviews() {
  await ensureSchema();
  const sql = getDb();
  const rows = await sql<ReviewRow[]>`
    select id, name, company, date_label, rating, text, initials, status, created_at
    from site_reviews
    where status = 'published'
    order by created_at desc, id desc
    limit 50
  `;

  return rows.map((row) => ({
    id: row.id,
    name: row.name,
    company: row.company || "Client",
    date: row.date_label,
    rating: row.rating,
    text: row.text,
    initials: row.initials || buildInitials(row.name),
  })) satisfies ReviewItem[];
}

export async function createReview(input: {
  name?: string;
  company?: string;
  text: string;
  rating: number;
}) {
  await ensureSchema();
  const sql = getDb();
  const name = input.name?.trim() || "Anonymous";
  const company = input.company?.trim() || "Client";
  const dateLabel = new Date().toLocaleDateString("en-US", {
    month: "long",
    year: "numeric",
  });

  await sql`
    insert into site_reviews (name, company, date_label, rating, text, initials, status)
    values (
      ${name},
      ${company},
      ${dateLabel},
      ${Math.min(Math.max(Math.round(input.rating || 5), 1), 5)},
      ${input.text.trim()},
      ${buildInitials(name)},
      'published'
    )
  `;
}

export async function listContactSubmissions() {
  await ensureSchema();
  const sql = getDb();

  const rows = await sql<ContactRow[]>`
    select id, full_name, email, phone, inquiry_type, subject, message, attachment_name, status, created_at
    from contact_submissions
    order by created_at desc, id desc
    limit 50
  `;

  return rows;
}

export async function createContactSubmission(input: {
  fullName: string;
  email: string;
  phone?: string;
  inquiryType?: string;
  subject: string;
  message: string;
  attachmentName?: string;
}) {
  await ensureSchema();
  const sql = getDb();

  await sql`
    insert into contact_submissions (
      full_name,
      email,
      phone,
      inquiry_type,
      subject,
      message,
      attachment_name,
      status
    )
    values (
      ${input.fullName.trim()},
      ${input.email.trim()},
      ${input.phone?.trim() || null},
      ${input.inquiryType?.trim() || null},
      ${input.subject.trim()},
      ${input.message.trim()},
      ${input.attachmentName?.trim() || null},
      'new'
    )
  `;
}

export async function getAdminDashboardCounts() {
  await ensureSchema();
  const sql = getDb();

  const [reviewsCount, contactsCount, contentRows] = await Promise.all([
    sql<{ count: string }[]>`
      select count(*)::text as count
      from site_reviews
    `,
    sql<{ count: string }[]>`
      select count(*)::text as count
      from contact_submissions
    `,
    sql<{ updated_at: string }[]>`
      select updated_at
      from site_content
      where slug = 'home'
      limit 1
    `,
  ]);

  return {
    reviews: Number(reviewsCount[0]?.count ?? 0),
    contacts: Number(contactsCount[0]?.count ?? 0),
    lastUpdated: contentRows[0]?.updated_at ?? new Date().toISOString(),
  };
}
